name:                aoc2018
version:             0.1.0.0
github:              "mstksg/advent-of-code-2018"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: |
    It's the Advent of Code 2018!

ghc-options:
- -Wall
- -Wcompat

dependencies:
- base >= 4.7 && < 5
- finite-typelits
- containers
- deepseq
- text

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - curl
  - directory
  - filepath
  - haskell-names
  - haskell-src-exts
  - hpack
  - lens
  - megaparsec
  - pointedlist
  - split
  - template-haskell
  - transformers
  - yaml
  default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - EmptyCase
  - GADTs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiWayIf
  - NumDecimals
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeInType
  - ViewPatterns

executables:
  aoc2018:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-terminal
    - aoc2018
    - criterion
    - optparse-applicative
    - time

# tests:
#   aoc2018-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - aoc2018
